### ISSUE TITLE
Is the API down?

### ISSUE THREAD

**Issue by sert23** [seandavi/SRAdbV2#20]
Hello Sean, great piece of work here, I'm finding this package really useful for my research.

Is it possible that the API is down? I can't connect. Even if I use my browser with this website: https://api-omicidx.cancerdatasci.org/sra/1.0/ui/

Thanks for making this package!

**Comment by vjcitn** [comment]
Take a look at https://omicidx-test.cancerdatasci.org/docs

I think the R client needs to be retooled somewhat to use the API through this route.  For now I am finding it expeditious to work directly with the API described at the URL just above via httr

**Comment by chiyuhao** [comment]
I have tried to connect to this website and can't visit this url either. 
The error message is: Error in curl::curl_fetch_memory(url, handle = handle) : Timeout was reached: [api-omicidx.cancerdatasci.org] Connection timed out after 10001 milliseconds.
I have also tried to use a proxy in R to visit api-omicidx.cancerdatasci.org, it also failed. Do you know how to handle this problem? Thanks.

**Comment by sert23** [comment]
I think Sean moved on to develop SRAdbV2 with a different approach.
Please check this https://twitter.com/seandavis12/status/1174767950596890625
and maybe this https://github.com/seandavi/omicidx

It was already a few months since I used this so I don't remember exactly but it was somehow using the Google Cloud

**Comment by seandavi** [comment]
Sorry, all. We did some substantial updates and changes. 

- https://github.com/omicidx/omicidx
- http://api.omicidx.cancerdatasci.org/redoc
