### ISSUE TITLE
size=500L in example yields result with 8516 records

### ISSUE THREAD

**Issue by vjcitn** [seandavi/SRAdbV2#5]
using  https://github.com/seandavi/SRAdbV2#using-the--new-interface

the setting of size is 500L but the value of z$count() is 8516

**Comment by seandavi** [comment]
Documentation issue, I think. `count` is a count of the total records found. `size` is the number of records returned by simple `results`.

```
> res = z$results()
> dim(z)
NULL
> dim(res)
[1] 500  88
> attr(res,'count')
[1] 277697
> z$size=200
> res = z$results()
> dim(res)
[1] 200  88
> attr(res,'count')
[1] 277697
```
