### ISSUE TITLE
Missing metadata

### ISSUE THREAD

**Issue by yosch123** [seandavi/SRAdbV2#7]
Hi,

Similar to a previous issue, I've also been having trouble with missing metadata. Specifically, I've been trying to find studies with GSE accession numbers. Many of the ones that I've searched for are missing, even though I found them in NCBI. For example,

GSE103763
GSE84214
GSE48121
GSE36854
GSE3442

Thanks!

**Comment by seandavi** [comment]
Thanks, @yosch123, for the report. This is a bit complicated. First, I see these accessions:

- https://api-omicidx.cancerdatasci.org/sra/1.0/search/full?q=GSE103763&size=10

The GSE84214 accession is for a superseries, composed of:

- https://api-omicidx.cancerdatasci.org/sra/1.0/search/full?q=GSE84209&size=10
- https://api-omicidx.cancerdatasci.org/sra/1.0/search/full?q=GSE84210&size=10
- https://api-omicidx.cancerdatasci.org/sra/1.0/search/full?q=GSE84211&size=10

The way that NCBI GEO stores these super/subseries records is not consistent with the way that SRA stores the records. In short, until I pull metadata from another GEO database, the superseries do not show up in the SRA at all.

Finally, the last accessions (GSE48121, GSE36854, GSE3442) are all microarray studies, so they are not stored in SRA, which stores only sequence data. 

Hope that helps clarify what is going on a bit. Feel free to continue the conversation here if needed.

**Comment by yosch123** [comment]
Thanks @seandavi  for the followup! I assume there's no way, then, to know with sradb whether the accession number is a superseries. 

For the GSE103763, I can't find it using the getSRA function in my script. My line of code is simply 

info1 <- SRAdb::getSRA(search_terms = "GSE103763", out_types = c("sra"),sra_con = sra_con)

which works with other GSE numbers but not this one

**Comment by seandavi** [comment]
Unfortunately, that is true. We pull the data for both SRAdb and SRAdbV2 from SRA only (as of now). At some unspecified time in the future, we will be integrating GEO and SRA metadata, but....

Sorry about the edge case--NCBI data models are not always consistent across databases and we are seeing that here.

**Comment by yosch123** [comment]
Ok, thanks. Just curious, what is the api-omicidx website that you linked to and why was that able to find the GSE103763?

**Comment by seandavi** [comment]
The website is an in-development replacement for SRAdb. The SRAdb approach is pretty fragile and does not always get updated appropriately. In addition, SRAdb is quite large for download these days, so for some folks, have an API is perhaps advantageous.
